### PR TITLE
Add options for rfc2217 and socket

### PR DESCRIPTION
**Pull request by WillCodeForCats**

### CODE REVIEW

**Comment by jamestalmage** [comment]
Cool!

Is there a way for me to point my HA instance at this PR/branch for testing?

**Comment by WillCodeForCats** [comment]
No, you would have to manually install it until a package is built, which won't happen until I'm satisfied with my testing.

**Comment by jamestalmage** [comment]
> No, you would have to manually install it

I did. Took me way too much time to figure out that I had to comment out the pointers to your docker images so it would actually build from source. (It says so right in the add on developer docs, but I missed it). 

It is early, but so far, running smoothly with 14 thermostats and a DHW setpoint control.

**Comment by WillCodeForCats** [comment]
Good to hear; let me know if any problems come up but if nothing does I'll probably merge it in a week or two.

**Comment by WillCodeForCats** [comment]
Are you using it in rfc2217 or socket mode?

**Comment by jamestalmage** [comment]
Socket mode.

I didn't even look into what RFC2217 was.

**Comment by jamestalmage** [comment]
So,
It appears to stop responding to attempts to change the heat setpoint after some time. Works initially, then just stops. I adjust the slider (from 64˚F to 66˚F), it is red for a moment (showing the new setpoint), quickly goes to black (still showing the new setpoint), and within 10 seconds, it shows the original setpoint. The setpoint on the device never changes.

I'm pretty familiar with the underlying protocol at this point (my JS implementation is nearly done). Is there a way for me to look at the underlying byte stream in the logs? I turned on debug logging in the HAS UI, but I'm not seeing much.

Important note: I'm running this branch merged with master. Seems like the only commits this branch is behind on were build-tool related, so I don't think it matters. But if I'm missing something and should try this branch is, I'm happy to try that. Also, I installed the integration via HACS, so that part is running whatever is latest in that repository. I didn't see anything in the commit logs that appeared to affect this, but if you think I'm missing something, let me know.

**Comment by jamestalmage** [comment]
Additionally, RFC2217 just didn't work... At all.

**Comment by jamestalmage** [comment]
Error messages in `tekmar-packetserv` 

> 2023-06-14 13:01:07.869773: Connected to 172.30.32.1:38668
> 2023-06-14 14:13:26.245190: read failed: [Errno 110] Operation timed out
> 2023-06-14 14:13:26.245235: Serial port closing.

It stopped responding well before that

**Comment by WillCodeForCats** [comment]
That means the connection to the serial device was lost.

**Comment by jamestalmage** [comment]
How is `tekmar-packetserv` formatting the output to/from the integration.

Looks like newline delimited hex strings? 

Just the TRPC data? Or is it the whole packet? In other words is it (SOF, LENGTH, TYPE, DATA, CS, EOF), or just (DATA) that is getting transmitted.

Same for integration-to-serial communication? (Same formatting?)

**Comment by WillCodeForCats** [comment]
I don't remember, it's been too long since I implemented that part. Probably whole.

**Comment by jamestalmage** [comment]
I am running all of this in a VM on my laptop. Just testing for now. Entirely possible that timeouts are being induced by sleep states. Just plugged into a wall and disabled sleep. Will update.

Regardless, there's probably some sort of reconnect needed.

**Comment by WillCodeForCats** [comment]
I'll have to try and duplicate the connection loss.

**Comment by jamestalmage** [comment]
Good news is that it appears that disabling sleep fixed it.

**Comment by WillCodeForCats** [comment]
Watchdog reloading should be addressed as part of the s6 overlay update in PR #40

**Pull request merged**
